Repository SEP4-DK1/SEP4-FRONTEND-TS, pull requests merged in 2023-05, with the labels that each got.

#1 Finished for now.
  src/components/LiveValue/LiveValue.css
  src/components/LiveValue/LiveValue.test.tsx
  src/components/LiveValue/LiveValue.tsx
Labels: enhancement

#2 Feature edit values
  src/App.test.tsx
  src/App.tsx
  src/components/EditValues/EditValues.css
  src/components/EditValues/EditValues.test.tsx
  src/components/EditValues/EditValues.tsx
  src/components/config.ts
Labels: WIP, Component

#4 Feature login status
  package-lock.json
  package.json
  src/App.tsx
  src/components/LoginStatus/LoginStatus.css
  src/components/LoginStatus/LoginStatus.test.tsx
  src/components/LoginStatus/LoginStatus.tsx
  src/components/config.ts
  src/img/profile.svg
Labels: WIP, Component

#5 Feature collapsible menu
  package-lock.json
  package.json
  src/App.tsx
  src/components/CollapsibleMenu/CollapsibleMenu.css
  src/components/CollapsibleMenu/CollapsibleMenu.test.tsx
  src/components/CollapsibleMenu/CollapsibleMenu.tsx
  src/components/LoginStatus/LoginStatus.test.tsx
Labels: WIP, Component

#6 CollapsibleMenu - Now gets menu items from config
  src/App.tsx
  src/components/CollapsibleMenu/CollapsibleMenu.tsx
  src/components/config.ts
Labels: Done, Improvement

#7 Feature live graph pull request into dev branch
  package-lock.json
  package.json
  src/App.tsx
  src/components/LiveGraph/LiveGraph.css
  src/components/LiveGraph/LiveGraph.test.tsx
  src/components/LiveGraph/LiveGraph.tsx
Labels: WIP, Component

#8 Feature navbar
  package-lock.json
  src/App.tsx
  src/components/LoginStatus/LoginStatus.css
  src/components/LoginStatus/LoginStatus.tsx
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.tsx
Labels: WIP, Component

#9 Feature live page
  src/App.css
  src/App.tsx
  src/components/EditValues/EditValues.css
  src/components/LiveGraph/LiveGraph.css
  src/components/LiveGraph/LiveGraph.tsx
  src/components/LiveValue/LiveValue.css
  src/components/LiveValue/LiveValue.tsx
  src/components/config.ts
  src/index.css
  src/routes/Live.js.tsx
  src/routes/LivePage/LivePage.css
  src/routes/LivePage/LivePage.tsx
Labels: WIP, Component

#10 CollapisbleMenu - test didn't work
  src/components/CollapsibleMenu/CollapsibleMenu.test.tsx
  src/components/CollapsibleMenu/CollapsibleMenu.tsx
  src/components/EditValues/EditValues.test.tsx
Labels: Bug, Done

#12 Improve LiveValue with Connection Status
  src/components/LiveValue/LiveValue.css
  src/components/LiveValue/LiveValue.tsx
Labels: Done, Improvement

#13 Improved LiveValue to use CSS Modules instead of CSS stylesheet
  src/components/LiveValue/LiveValue.module.css
  src/components/LiveValue/LiveValue.tsx
Labels: Done, Improvement

#14 Feature title cards
  src/App.tsx
  src/components/TitleCard/TitleCard.css
  src/components/TitleCard/TitleCard.test.tsx
  src/components/TitleCard/TitleCard.tsx
Labels: WIP, Component

#15 Feature carousel
  package-lock.json
  package.json
  src/App.tsx
  src/components/Carousel/Carousel.css
  src/components/Carousel/Carousel.tsx
  src/components/config.ts
Labels: Component, Done

#18 Improved EditValues with CSS Module + Restyling
  src/components/EditValues/EditValues.css
  src/components/EditValues/EditValues.module.css
  src/components/EditValues/EditValues.tsx
  src/img/icons/humidity.png
  src/img/icons/send.png
  src/img/icons/temperature.png
Labels: Done, Improvement

#19 Improved LoginStatus with CSS Module + Restyling
  .idea/prettier.xml
  .idea/vcs.xml
  package-lock.json
  package.json
  src/components/LoginStatus/LoginStatus.css
  src/components/LoginStatus/LoginStatus.module.css
  src/components/LoginStatus/LoginStatus.test.tsx
  src/components/LoginStatus/LoginStatus.tsx
  src/img/icons/user.png
  src/img/profile.svg
Labels: Done, Improvement

#22 Improved LiveGraph with CSS Module + Restyling
  src/components/LiveGraph/LiveGraph.css
  src/components/LiveGraph/LiveGraph.module.css
  src/components/LiveGraph/LiveGraph.tsx
Labels: Improvement

#21 Improved Navbar with CSS Module + Restyling
  src/components/Navbar/Navbar.module.css
  src/components/Navbar/Navbar.tsx
Labels: Done, Improvement

#23 Hotfix live graphs co2
  src/components/LiveValue/LiveValue.module.css
  src/components/LiveValue/LiveValue.tsx
Labels: Bug, WIP

#25 Feature selcted bread profiles
  src/App.tsx
  src/components/LoginStatus/LoginStatus.tsx
  src/components/SelcetedBreadProfiles/SelcetedBreadProfiles.css
  src/components/SelcetedBreadProfiles/SelcetedBreadProfiles.tsx
Labels: WIP, Component

#26 Improved LiveValues Initial data
  src/components/LiveValue/LiveValue.tsx
Labels: Done, Improvement

#27 Feature live graph with live data
  src/components/LiveGraph/LiveGraph.tsx
  src/components/LiveValue/LiveValue.tsx
Labels: Component, Done

#28 Hotfix of LiveGraph
  src/components/LiveGraph/LiveGraph.tsx
Labels: Bug, Done

#29 Workflows might work now?
  .gitignore
  src/App.test.tsx
  src/components/LiveGraph/LiveGraph.test.tsx
  src/components/LiveValue/LiveValue.test.tsx
Labels: Documentation

#31 Fixed issue where Carousel overlaped the CollapsibleMenu
  src/components/Carousel/Carousel.css
  src/components/CollapsibleMenu/CollapsibleMenu.module.css
Labels: Bug, WIP

#32 Feature history graphs
  src/App.tsx
  src/components/HistoryGraph/HistoryGraph.module.css
  src/components/HistoryGraph/HistoryGraph.tsx
  src/img/icons/blueCalendar.png
  src/img/icons/blueClock.png
  src/img/icons/redCalendar.png
  src/img/icons/redClock.png
Labels: Component, Done

#33 Fixed the Bug with Carbon showing PPM...
  src/components/LiveGraph/LiveGraph.tsx
  src/components/LiveValue/LiveValue.tsx
Labels: Bug, Done

#34 Feature login page
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/components/LoginStatus/LoginStatus.tsx
  src/components/config.ts
  src/routes/Login/LoginPage.module.css
  src/routes/Login/LoginPage.tsx
Labels: WIP, Component

#35 Fixed LiveValues + LiveGraphs rounding error.
  src/components/LiveGraph/LiveGraph.tsx
  src/components/LiveValue/LiveValue.tsx
Labels: Bug

#36 Feature ghpages
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/components/config.ts
  tsconfig.json
Labels: WIP, Component

#37 Feature bread profiles page
  src/App.tsx
  src/components/SelcetedBreadProfiles/SelcetedBreadProfiles.css
  src/components/SelcetedBreadProfiles/SelcetedBreadProfiles.tsx
  src/components/SelectedBreadProfile/SelectedBreadProfile.module.css
  src/components/SelectedBreadProfile/SelectedBreadProfile.tsx
  src/components/TargetCard/TargetCard.css
  src/components/TargetCard/TargetCard.module.css
  src/components/TargetCard/TargetCard.test.tsx
  src/components/TargetCard/TargetCard.tsx
  src/components/config.ts
  src/routes/BreadProfilesPage/BreadProfilesPage.module.css
  src/routes/BreadProfilesPage/BreadProfilesPage.tsx
  src/routes/Landing/Landing.tsx
Labels: Component, Done

#38 Improve pages authentication
  package-lock.json
  package.json
  src/App.tsx
  src/components/HistoryGraph/HistoryGraph.tsx
  src/components/LoginStatus/LoginStatus.tsx
  src/components/config.ts
  src/components/login.ts
  src/routes/BreadProfilesPage/BreadProfilesPage.tsx
  src/routes/Landing/Landing.tsx
  src/routes/LivePage/LivePage.tsx
  src/routes/Login/LoginPage.tsx
Labels: WIP, Improvement

#40 Formatted time in many components
  src/components/EditValues/EditValues.tsx
  src/components/SelectedBreadProfile/SelectedBreadProfile.tsx
  src/components/TargetCard/TargetCard.tsx
  src/components/config.ts
  src/routes/BreadProfilesPage/BreadProfilesPage.tsx
Labels: Component, Done

#41 Hotfix not working
  src/components/LiveValue/LiveValue.tsx
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.module.css
  src/components/Navbar/Navbar.tsx
  src/components/SelectedBreadProfile/SelectedBreadProfile.module.css
  src/components/SelectedBreadProfile/SelectedBreadProfile.tsx
  src/components/TargetCard/TargetCard.tsx
  src/components/config.ts
  src/img/TitleCardImages/Live.jpg
  src/routes/BreadProfilesPage/BreadProfilesPage.tsx
Labels: Bug

#42 PostTarget
  package-lock.json
  package.json
  src/routes/BreadProfilesPage/BreadProfilesPage.tsx
Labels: Bug, Done

#43 Adding back a lot of test + some new ones.
  src/components/HistoryGraph/HistoryGraph.test.tsx
  src/components/HistoryGraph/HistoryGraph.tsx
  src/components/LiveGraph/LiveGraph.test.tsx
  src/components/LiveValue/LiveValue.test.tsx
  src/components/SelectedBreadProfile/SelectedBreadProfile.test.tsx
  src/components/SelectedBreadProfile/SelectedBreadProfile.tsx
  src/components/TargetCard/TargetCard.test.tsx
  src/routes/BreadProfilesPage/BreadProfilesPage.tsx
Labels: Done, Improvement

#44 HotFix
  src/components/SelectedBreadProfile/SelectedBreadProfile.tsx
  src/components/TargetCard/TargetCard.tsx
  src/routes/BreadProfilesPage/BreadProfilesPage.tsx
Labels: Bug, Done

#46 css for SaveButton
  src/components/EditValues/EditValues.module.css
Labels: Done, Improvement
